//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Игра.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Игра.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Точки кипения
        ///Точки зрения
        ///Точки опоры
        ///Точки розничной торговли
        ///В домик Наф-Нафа
        ///В Форт-Нокс
        ///В Трою
        ///В женский монастырь
        ///К морю
        ///К свадьбе
        ///К славе
        ///К звездам
        ///Книгу с фотокарточками
        ///Собрание музыки
        ///Тетрадь для рисования
        ///Диплом
        ///Сметану
        ///Чай
        ///Соль
        ///Макароны
        ///Из мрамора
        ///Из гранита
        ///Из дерева
        ///Из камня
        ///Аргентина
        ///Непал
        ///Швейцария
        ///Ливия
        ///Москва
        ///Суздаль
        ///Хельсинки
        ///Санкт-Петербург
        ///Первое покорение Эвереста
        ///Первый спуск в Марианскую впадину
        ///Достижение Южного магнитного полюса
        ///Полет первого брит [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string answers {
            get {
                return ResourceManager.GetString("answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap call {
            get {
                object obj = ResourceManager.GetObject("call", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fifty {
            get {
                object obj = ResourceManager.GetObject("fifty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на С помощью какой точки Архимед собирался перевернуть рычагом Землю?
        ///Куда безуспешно пытался проникнуть волк в сказке о трех поросятах?
        ///Каким словом завершается устойчивое выражение о трудном пути к прекрасному: «Через тернии…»?
        ///Что не называют альбомом?
        ///Что обычно не продают в бакалейном отделе магазина?
        ///Из чего в 1924 году был построен первый вариант Мавзолея Ленина?
        ///Флаг какой страны квадратный?
        ///Какой город стал столицей России в 1712 году?
        ///Какое из этих событий было приурочено ко дню коронации Ели [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string questions {
            get {
                return ResourceManager.GetString("questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Точки опоры
        ///В домик Наф-Нафа
        ///К звездам
        ///Диплом
        ///Сметану
        ///Из дерева
        ///Швейцария
        ///Санкт-Петербург
        ///Первое покорение Эвереста
        ///Кимчи
        ///Неприятности
        ///Южная Америка
        ///С мельницами
        ///Слепой
        ///Голубая кровь.
        /// </summary>
        internal static string true_answers {
            get {
                return ResourceManager.GetString("true_answers", resourceCulture);
            }
        }
    }
}
